#!/usr/bin/env bash
# Generates THIRD-PARTY-NOTICES.md — Apache-2.0 §4 attribution for the
# dependencies bundled into release artifacts (hub and gateway binaries, UI
# bundle). Regenerate with `make notices`; RELEASE-CHECKLIST.md requires a
# fresh run before every cut.
set -euo pipefail
cd "$(dirname "$0")/../.."

OUT=THIRD-PARTY-NOTICES.md
GO_LICENSES="go run github.com/google/go-licenses@v1.6.0"

go_report() { # $1 = module dir
  # CSV: module,license-url,license-id → markdown table rows, sorted.
  # First-party packages (this repo, AGPL) are excluded — the file lists
  # third-party attribution only.
  (cd "$1" && eval "$GO_LICENSES report ./..." 2>/dev/null) \
    | grep -v '^github.com/avuru/avuru-obs' \
    | sort -u \
    | awk -F, '
        # go-licenses reports per package; subpackages of a module whose
        # LICENSE sits at the module root come back "Unknown". Verified
        # overrides for those (license at the module root):
        /^github\.com\/segmentio\/asm\// { $3 = "MIT" }
        { printf "| %s | %s |\n", $1, $3 }'
}

{
  echo "# Third-party notices"
  echo
  echo "Licenses of third-party code bundled into Avuru Obs release artifacts."
  echo "Avuru Obs itself is [AGPL-3.0](LICENSE) — see [LICENSING.md](LICENSING.md)."
  echo "Generated by \`make notices\`; do not edit by hand."
  echo
  echo "## Hub (Go)"
  echo
  echo "| Module | License |"
  echo "|---|---|"
  go_report hub
  echo
  echo "## Gateway sentryreceiver (Go)"
  echo
  echo "| Module | License |"
  echo "|---|---|"
  go_report gateway/sentryreceiver
  echo
  echo "The gateway binary additionally bundles the OpenTelemetry Collector"
  echo "modules pinned in [gateway/ocb-manifest.yaml](gateway/ocb-manifest.yaml),"
  echo "all Apache-2.0."
  echo
  echo "## Grafana data source backend (Go)"
  echo
  echo "| Module | License |"
  echo "|---|---|"
  go_report clients/grafana-datasource
  echo
  echo "The \`avuruobs\` CLI has no third-party dependencies, so it contributes"
  echo "no attribution here. The data source's FRONTEND bundle likewise ships"
  echo "none: every Grafana and React package it uses is external, resolved from"
  echo "the host at load time rather than bundled."
  echo
  echo "## UI (npm, production dependencies)"
  echo
  echo "| Package | License |"
  echo "|---|---|"
  (cd ui && npx --yes license-checker --production --csv 2>/dev/null) \
    | tail -n +2 \
    | grep -v '^"\{0,1\}@avuru/' \
    | awk -F, '{ gsub(/"/, ""); printf "| %s | %s |\n", $1, $2 }' \
    | sort -u
} > "$OUT"

echo "wrote $OUT ($(grep -c '^|' "$OUT") table rows)"
