{{- if and (not .Values.clickhouse.external.existingSecret) (not .Values.clickhouse.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avuruops.fullname" . }}-clickhouse
  labels:
    {{- include "avuruops.labels" . | nindent 4 }}
type: Opaque
stringData:
  clickhouse-password: {{ .Values.clickhouse.auth.password | quote }}
{{- end }}
