{{- if and (include "avuruops.oidcEnabled" .) .Values.auth.oidc.clientSecret (not .Values.auth.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avuruops.fullname" . }}-oidc
  labels:
    {{- include "avuruops.labels" . | nindent 4 }}
type: Opaque
data:
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
